server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**     
